server:
  port: 8501

spring:
  application:
    name: account-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/


spcloud:
  cassandra:
    contact:
      point: 172.17.0.2
    port: 9042
    keyspace:
      name: springcloud

    password: password
    username: cassandra