server:
  port: 8502

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_database
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
        ddl-auto: update
  rabbitmq:
    username: guest
    password: guest
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"



  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
eureka:
  client:
    instance:
      hostname: http://localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

  zipkin:
    base-url: http://localhost:9411/
