server:
  port: 8502

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://172.23.0.3:3306/microservice-app
    username: root
    password: sp-cloud
  jpa:
    database: mysql
    hibernate:
        ddl-auto: update
eureka:
  client:
    instance:
      hostname: http://localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/


