version: 3
services:
  cassandra:
    image: cassandra
    ports:
      -'9042':'9042'

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sp-cloud

  elasticsearch:
    image: elasticsearch:6.8.5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node